### ISSUE TITLE
Inference not working cause of CausalVideoAutoencoder

### ISSUE THREAD

**Issue by Husky110** [newgenai79/LTXVideo#2]
Hi - I've tried following your tutorial and try to run your example-config.  
I didn't use conda, but python-venv.
Now keeping the config.yaml the same as here, when I run `python inference.py` it fails with this:
```
Traceback (most recent call last):
  File "/home/kasm-user/LTXVideo/inference.py", line 369, in <module>
    main()
  File "/home/kasm-user/LTXVideo/inference.py", line 231, in main
    vae = load_vae(vae_dir)
  File "/home/kasm-user/LTXVideo/inference.py", line 38, in load_vae
    vae = CausalVideoAutoencoder.from_config(vae_config)
  File "/home/kasm-user/LTXVideo/ltx_video/models/autoencoders/causal_video_autoencoder.py", line 65, in from_config
    config["_class_name"] == "CausalVideoAutoencoder"
AssertionError: config must have _class_name=CausalVideoAutoencoder
```
System is Ubuntu 22.04.

**Comment by newgenai79** [comment]
Hello Lothar,

I am preparing a new guide and git repo which should work fine. Even though
I create videos for Windows users, it should work on Linux.

Please wait for a day or 2.

Thanks

**Comment by Husky110** [comment]
Sure thing. 
Could you please try to use python venv and link the new video here when you are done?

**Comment by newgenai79** [comment]
Please refer this. Let me know if it is working now.
https://youtu.be/4Wo1Kgluzd4

**Comment by Husky110** [comment]
Yep - works like a charm. :)
But I think your approach of shoving multiple tools into one virtual-environment will fail ultimately. You will run into conflicting requirements soon and that will break your project.
What I did was setting up a workspace in docker (via KASM-Workspaces) and got a venv for every tool in there which is linked through a volume to the host-machine, so it doesn't need to be rebuild all the time. Might be a good idea for you too.

**Comment by newgenai79** [comment]
> But I think your approach of shoving multiple tools into one virtual-environment will fail ultimately. You will run into conflicting requirements soon and that will break your project. 

Gonna try the most diffuser supported models. 3 supported for now, let's see.
